# Site settings
title: MasterKe's Blog
SEOTitle: MasterKe | 柯大师
header-img: img/home-bg.jpg
email: masterke@icloud.com
description: "柯大师的博客，记录生活、技术、读书"
keyword: "柯大师, MasterKe, 博客, 个人网站, 互联网, Web开发"
url: "https://blog.masterke.cn"
baseurl: ""
timezone: Asia/Shanghai

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username: masterke2023
# zhihu_username: masterke2023
github_username: MasterKe2003
#twitter_username:  masterke
#facebook_username:  masterke



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: masterkeblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "导航页：https://masterke.cn"
sidebar-avatar: /img/logo.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "flexd",
        href: "https://flexd1.github.io/"
    }
]